name: stadium_eye
description: "Stadium Eye project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  bloc: ^9.1.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.0
  dotted_border: ^3.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  get_it: ^9.2.0
  http: ^1.6.0
  iconsax_flutter: ^1.0.1
  internet_connection_checker_plus: ^2.9.1
  intl: ^0.20.2
  lottie: ^3.3.2
  persistent_bottom_nav_bar_v2: ^6.2.0
  shared_preferences: ^2.2.2
  video_player: ^2.10.1
  flutter_otp_text_field: ^1.5.1+1
  skeletonizer: ^2.1.1
  # liquid_pull_refresh: ^1.0.6
  animated_text_kit: ^4.3.0
  image_picker: ^1.2.1
  file_picker: ^10.3.7
  path: ^1.9.1
  custom_refresh_indicator: ^4.0.1
  awesome_dialog: ^3.3.0
  
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/stadium_light.jpeg
    - assets/images/stadium_night.jpeg
    - assets/images/logo_app.jpg
    - assets/images/
    # - assets/images/
    - assets/videos/
    - assets/lottie/RollingFootbll.json
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  template_arbs: [app_en.arb]
  output_dir: lib/l10n/generated
