name: Stadium Eye CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the project
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install Flutter 3.38.1
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.1'
          channel: stable

      # 3. Install pub dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Check code quality
     # - name: Run Analyzer
     #   run: flutter analyze

      # 5. Run Tests (if any exist)
    #   - name: Run Tests
    #     run: flutter test

      # 6. Build Android APK (Debug)
      # - name: Build APK (Debug)
      #   run: flutter build apk --debug
      
      # 6. Build Android APK (Release)
      - name: Build APK (Release)
        run: flutter build apk --release

      # 7. Save APK artifact
      # - name: Upload APK artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: stadium-eye-debug-apk
      #     path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: stadium-eye-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
